# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 845a957c3feff3f302a825451e486ee1f30ea3721b1101e13e75078b6cb7b40e943e043ff354bf868e58ae937674996d7d41706a3f8ca1b0e6a7cec4e06fb881

test:
  secret_key_base: 012d801405fd4e923c3e8bad012694f547495d1e98f18759242a9971dedb96809d27365facbaa00f066c820861a77a7574a7b042bc1cb456ddabbb541bd1a7b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
